# Generated by Django 4.0.4 on 2022-04-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_blogpost_image_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1024)),
                ('media', models.FileField(blank=True, upload_to='profile_pics')),
                ('contenttype', models.CharField(choices=[('TXT', 'Text'), ('IMG', 'Image'), ('VID', 'Video')], default='IMG', max_length=3)),
                ('order', models.IntegerField(default=0)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blogpost')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
