# Generated by Django 4.0.4 on 2022-04-23 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_postblock_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='PostBlock',
        ),
    ]
