# Generated by Django 4.0.4 on 2022-04-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_blogpost_content1_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content1',
            field=models.TextField(blank=True),
        ),
    ]
